### ISSUE TITLE
Help needed local install

### ISSUE THREAD

**Issue by a1nb0** [itemsapi/curlist#14]
Hi @cigolpl,

I try to install it locally on my mac, i already have node, npm, sqlite elasticsearch and redis installed
And i get an error when i run:
git clone git@github.com:itemsapi/curlist.git

Cloning into 'curlist'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists..
And then i tried:
 git clone https://github.com/itemsapi/curlist.git 
![screen shot 2018-07-23 at 5 36 51 pm](https://user-images.githubusercontent.com/37039235/43083388-06f82faa-8e9f-11e8-8c49-37b8ae8f1d50.png)

**Comment by cigolpl** [comment]
Hello @a1nb0,

I guess your local git is not configured. Check this https://help.github.com/articles/error-permission-denied-publickey/.

You can also try this `git clone https://github.com/itemsapi/curlist.git` and it should work immediately but if you configure git then `git clone git@github.com:itemsapi/curlist.git` is more convenient

**Comment by a1nb0** [comment]
yes i did that it worked but threw errors afterwards when i run npm install

![screen shot 2018-07-23 at 6 10 54 pm](https://user-images.githubusercontent.com/37039235/43085498-cc050378-8ea3-11e8-8984-ee4ea56b5f4c.png)

**Comment by cigolpl** [comment]
A few ideas:

- let's try to install `npm install pg@7.4.1` or `npm install pg-native@2.2.0`. If any of them are throwing errors then they are causes of the problem

- if the `pg-native` is a problem, let's try to delete a line in package.json with "pg-native": "^2.2.0" and `npm install` again. As far as I remember the pg-native is needed for heroku to make psql working and it's making troubles

**Comment by a1nb0** [comment]
npm install pg@7.4.1
![screen shot 2018-07-23 at 6 49 25 pm](https://user-images.githubusercontent.com/37039235/43087719-2cfaeeb8-8ea9-11e8-9a7c-111ca2ceafcc.png)

**Comment by a1nb0** [comment]
Deleted both from package.json
run again npm install
![screen shot 2018-07-23 at 6 57 09 pm](https://user-images.githubusercontent.com/37039235/43088245-5e6b9e6a-8eaa-11e8-8155-a4af1aa942fc.png)
![screen shot 2018-07-23 at 6 57 42 pm](https://user-images.githubusercontent.com/37039235/43088256-62f434e2-8eaa-11e8-9c7e-25267c5f34d8.png)

**Comment by cigolpl** [comment]
It's seems to be installed ok now. Which version of Elasticsearch you have ?

**Comment by a1nb0** [comment]
curl localhost:9200
curl: (7) Failed to connect to localhost port 9200: Connection refused

**Comment by cigolpl** [comment]
Your Elasticsearch is not turned on. On ubuntu I run it like that `sudo service elasticsearch start`. Not sure exactly how to run it on mac.

I am afraid this system is too complex or too alpha at the moment. Maybe it would be better if I provide you more information / tutorial once I make a next progress with that ? I don't want you to make lot of manual and "hacky" things

**Comment by a1nb0** [comment]
ok, it seems fair.
Let me ask you this.
Is there anything else from you have build that i could install  and use at this moment?

**Comment by cigolpl** [comment]
I don't know what to recommend. Each repo has a different purpose and I wouldn't call them super mature. What is your goal - creating a search app with similar features to http://devteams.co/ ?

**Comment by a1nb0** [comment]
well not necessarily  as complex.
what i am looking is just to build a tag search app nothing too advanced, it's just a personal project
So i would not need categories and full text search.
At a most basic level.
Add an item or a list of items to which i attach one or more tags.
When one of the tags is searched for the title is retrieved.
Of course the ability to cross search 2 or more tags will retrieve only the items meeting that criteria

I am looking for something like this for over a month now, i am tried a bunch of things and came to your project which i find to be very good for my needs.
I have read you blog posts, your 2015, 2016 tutorial tried to make them work but with no success.

I must admit i would really need some help :)

**Comment by cigolpl** [comment]
I see, thanks for details! What would be your main key / field in your dataset ? The curlist is supporting in the first stage "domain" key because I am working with the domains the most i.e. http://devteams.co/ is a list of companies but this is actually a list of domains. Similarly is with https://shoprank.co/. That's why I started here with a niche focus to speed up development and focus on core. 

Would you like to have end2end product where you install it, run it and you have a complete product (let's say as easy to start as google spreadsheet or wordpress?) which you can configure easily for your need or you also consider something very basic which you could extend by yourself with Node.js - maybe in other words how much are you familiar with programming in Node.js ?

**Comment by a1nb0** [comment]
i have created a chat room which i leve opened, if you have time join me and let's have a talk 
https://tlk.io/items

**Comment by a1nb0** [comment]
In the meantime i had some progress installing localhost
Here are the updates:

edited domains.yaml this is how they look 
![screen shot 2018-07-24 at 3 41 44 pm](https://user-images.githubusercontent.com/37039235/43138655-3cc2675e-8f58-11e8-84ab-7ae1540c1c14.png)
run : NODE_ENV=domains node_modules/.bin/sequelize db:migrate
threw an error that i need to install sqlite3 manually, i did install it 
![screen shot 2018-07-24 at 3 45 21 pm](https://user-images.githubusercontent.com/37039235/43138813-c41e14fa-8f58-11e8-8471-f8e2f79fd4f9.png)
and then run again NODE_ENV=domains node_modules/.bin/sequelize db:migrate
which seemed to work this time
![screen shot 2018-07-24 at 3 49 23 pm](https://user-images.githubusercontent.com/37039235/43138983-38a0de34-8f59-11e8-84b9-600e38c21ced.png)
then i run NODE_ENV=domains node scripts/db-to-es.js
where it threw an error
![screen shot 2018-07-24 at 3 50 01 pm](https://user-images.githubusercontent.com/37039235/43139043-69c31266-8f59-11e8-9657-68277050b8b5.png)
I am making progress, it would be awesome if we can make a chat again because only two steps left and i can run it localhost . 
I have that  chat window opened if you can connect

**Comment by cigolpl** [comment]
Looks coool! You need to install Redis. You can check if Redis is installed by `redis-cli -v`

**Comment by a1nb0** [comment]
rianas-MacBook-Air:curlist briana$ redis-cli -v
redis-cli 4.0.10
it is installed it seems

**Comment by a1nb0** [comment]
I will put the updates here so other people could use it too.
So At the previous step redis was not started
i run:  $ redis-server 
and it started
then i try to run again :
$ NODE_ENV=domains node scripts/db-to-es.js 
and it threw errors because elastic search was not running.
The solution to that was to  run
$ brew install elasticsearch
to which did not work the first time because i needed java  installed, i installed  running
$ brew cask install homebrew/cask-versions/java8
after rerun successfuly:
$ brew install elasticsearch
and then:
$ brew services start elasticsearch
![screen shot 2018-07-24 at 5 05 37 pm](https://user-images.githubusercontent.com/37039235/43143630-da41a700-8f63-11e8-8078-11971569d13c.png)
then tried again 
$ NODE_ENV=domains node scripts/db-to-es.js 
but i got a different error
![screen shot 2018-07-24 at 5 06 52 pm](https://user-images.githubusercontent.com/37039235/43143686-0487a3fc-8f64-11e8-9509-4ae029d99e58.png)
i am so close! :)

**Comment by cigolpl** [comment]
You need to downgrade Elasticsearch to version 1.7.x or 1.5.x then you should overcome this error

In my case I have ES 1.7.2:

![selection_714](https://user-images.githubusercontent.com/1032493/43150041-3bf4d8dc-8f69-11e8-925f-5948b31e6b68.png)

**Comment by a1nb0** [comment]
![screen shot 2018-07-24 at 6 53 43 pm](https://user-images.githubusercontent.com/37039235/43150620-0536f06e-8f73-11e8-9a8d-cd13a6d7e2a4.png)

**Comment by a1nb0** [comment]
So i tried installing the @2.4 and the run again
$ NODE_ENV=domains node scripts/db-to-es.js
That error is gone but i have something else
![screen shot 2018-07-24 at 7 14 13 pm](https://user-images.githubusercontent.com/37039235/43151971-e38089be-8f75-11e8-8098-c3aa9ec4586e.png)

**Comment by cigolpl** [comment]
On ubuntu I could install ES 1.7 like that:

```
wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.deb
sudo dpkg -i elasticsearch-1.7.2.deb
```

If ES 1.7 is not available on brew anymore then it's a problem. IMO there are two solution:
- maybe there is a custom brew or possibility to install ES 1.7 by file
- you can run ES with docker like that `docker run -d -p 127.0.0.1:9200:9200 elasticsearch:1.7.6` (more info https://github.com/itemsapi/itemsapi/blob/master/docs/ELASTICSEARCH.md)

**Comment by a1nb0** [comment]
i would a way to install 1.7.6 but i still get the same error
![screen shot 2018-07-24 at 7 44 35 pm](https://user-images.githubusercontent.com/37039235/43153508-25b08fa6-8f7a-11e8-9707-e3c4693eb6dc.png)

**Comment by cigolpl** [comment]
Please check if run version is 1.7.x with `curl localhost:9200`

**Comment by a1nb0** [comment]
nope 
Brianas-MacBook-Air:CURL2 briana$ curl localhost:9200
{
  "name" : "Z9PNc6D",
  "cluster_name" : "elasticsearch_briana",
  "cluster_uuid" : "XgkoE_nYTv6zhPB3uQ7kNQ",
  "version" : {
    "number" : "6.2.4",
    "build_hash" : "ccec39f",
    "build_date" : "2018-04-12T20:37:28.497551Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
Brianas-MacBook-Air:CURL2 briana$

**Comment by a1nb0** [comment]
i will uninstall and install again elastic search

**Comment by a1nb0** [comment]
Now check this out 
I start 1.7 then i run $NODE_ENV=domains node scripts/db-to-es.js
It throws a bunch of errors but when i try $ curl localhost:9200
I get 1.7.6 version
![screen shot 2018-07-24 at 8 48 05 pm](https://user-images.githubusercontent.com/37039235/43156505-fb96e496-8f82-11e8-8d96-e0819c233305.png)
![screen shot 2018-07-24 at 8 49 25 pm](https://user-images.githubusercontent.com/37039235/43156530-15fb1d34-8f83-11e8-86e7-22c9f0b9aae8.png)

Strange..

**Comment by a1nb0** [comment]
i also tried to run the next step $ PORT=3000 npm start
![screen shot 2018-07-25 at 9 11 17 am](https://user-images.githubusercontent.com/37039235/43182643-d258e7a6-8fea-11e8-9a8b-7e850d2520b2.png)

**Comment by cigolpl** [comment]
That's above with Elasticsearch is strange, because `curl localhost:9200` is working and Node.js is saying it's not working `Not living connections`. I don't know how to solve it right now. 

Please add:

```
db: 
  dialect: sqlite
  storage: './sqlite/database_domains.sqlite'
  database: database_example
  logging: false
```

Somewhere into `/config/domains.yaml` and run `npm start` again. Make sure migration was run `NODE_ENV=domains node_modules/.bin/sequelize db:migrate`

**Comment by a1nb0** [comment]
![screen shot 2018-07-25 at 9 50 54 am](https://user-images.githubusercontent.com/37039235/43184152-47161442-8ff0-11e8-912c-f76c799e3681.png)

**Comment by a1nb0** [comment]
The migrations worked but not npm start
![screen shot 2018-07-25 at 9 50 54 am](https://user-images.githubusercontent.com/37039235/43184235-9c7ba2f8-8ff0-11e8-8031-d076608eb8b1.png)

**Comment by a1nb0** [comment]
Edited domains.yaml
run $ NODE_ENV=domains node_modules/.bin/sequelize db:migrate
![screen shot 2018-07-25 at 9 58 21 am](https://user-images.githubusercontent.com/37039235/43184463-5a46bdfe-8ff1-11e8-8c61-38eef9ebcae2.png)
![screen shot 2018-07-25 at 10 00 26 am](https://user-images.githubusercontent.com/37039235/43184538-9918e494-8ff1-11e8-9879-5fbb32c9f863.png)
But running $ PORT=3000 npm start threw an error
![screen shot 2018-07-25 at 10 01 04 am](https://user-images.githubusercontent.com/37039235/43184597-cb0c8244-8ff1-11e8-8b27-f3c3e2e71415.png)

**Comment by cigolpl** [comment]
Curlist requires providing `NODE_ENV=domains` -> `NODE_ENV=domains PORT=3000 npm start` because it's responsible for loading specific configuration file i.e. `./config/domains.yaml`. If you don't provide it then it will load `./config/default.yaml` (more info: https://github.com/lorenwest/node-config/wiki/Configuration-Files)

**Comment by a1nb0** [comment]
So what step did i miss?

**Comment by a1nb0** [comment]
this is how my domains.yaml looks like
![screen shot 2018-07-25 at 10 16 00 am](https://user-images.githubusercontent.com/37039235/43185176-d2afae02-8ff3-11e8-9284-4c7a72fbc7ce.png)

**Comment by a1nb0** [comment]
Matt was really helpful, and we made it work 
i had to make some modifications in my domains.yaml  and then restart the app on a different port and it work perfectly!
![screen shot 2018-07-25 at 11 36 35 am](https://user-images.githubusercontent.com/37039235/43189342-050d22a2-8fff-11e8-8fdb-d814c6d0fc7e.png)
