### ISSUE TITLE
Deleting items stoped workig

### ISSUE THREAD

**Issue by a1nb0** [itemsapi/curlist#16]
I  added  over 1000 items
then deleted them by listing 1000/page and select all/ delete
And after that it threw an error , deleted only a part of them and now i can not delete the rest of them anymore
![screen shot 2018-07-25 at 4 58 09 pm](https://user-images.githubusercontent.com/37039235/43205533-43277e02-902c-11e8-9400-59afc3d0b178.png)
i restarted the app, run again command to delete the rest of them, but not, there is nothing in the terminal like it does not even register my request
![screen shot 2018-07-25 at 5 03 22 pm](https://user-images.githubusercontent.com/37039235/43205729-ad06591a-902c-11e8-8926-8e3ccc58d7a6.png)

LE: a strange behavior:
i manage to "delete" them if i try to add them again by importing the same .csv file used to add them the first time

![screen shot 2018-07-25 at 7 01 11 pm](https://user-images.githubusercontent.com/37039235/43212650-33b8eea4-903d-11e8-9461-e87cb34dbb07.png)

So it did not add anything but delete them instead(at least you do not see them on the index)
However, deleting or updating them does not remove them completely such that the id is still in the db

**Comment by cigolpl** [comment]
It might be a limit of hardware and I recommend removing smaller number of items. Otherwise if there is too much items then from some reason it's deleted from sqlite / psql but not from elasticsearch. In that case `NODE_ENV=domains node scripts/db-to-es.js` should solve the problem
